#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab
"""Aggregate G1 (Bonn SampEn) + G2 (AR A/B) confirmatory bundles -> honest verdict.

States: BRIGHT_LINE_PASSED | BRIGHT_LINE_NOT_PASSED | BLOCKED_DATA. No others.
No softening, no threshold change. Thresholds come from the pre-declared protocol.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BL = ROOT / "artifacts" / "bonn_bright_line"
CT = ROOT / "artifacts" / "controls"
G1 = BL / "bonn_CONFIRMATORY_VERDICT.json"
G2A = CT / "ar_negative_CONFIRMATORY_A.json"
G2B = CT / "ar_negative_CONFIRMATORY_B.json"

THRESH = 0.80   # pre-declared (BONN_BRIGHT_LINE_PROTOCOL.md)
MAX_FPR = 0.05


def _sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest() if p.is_file() else "MISSING"


def _load(p: Path):
    return json.loads(p.read_text(encoding="utf-8")) if p.is_file() else None


def main() -> int:
    g1, g2a, g2b = _load(G1), _load(G2A), _load(G2B)
    BL.mkdir(parents=True, exist_ok=True)
    if not (g1 and g2a and g2b):
        (BL / "BRIGHT_LINE_SUMMARY.json").write_text(json.dumps({
            "verdict": "BLOCKED_DATA", "reason": "confirmatory bundle(s) missing",
            "present": {"G1": bool(g1), "G2_A": bool(g2a), "G2_B": bool(g2b)}}, indent=2))
        print("BLOCKED_DATA")
        return 3

    gate = g1["bright_line"]
    frac_E = float(gate["frac_survived_E"])
    neg = gate.get("negative_sets", {})
    frac_A_not = float(neg.get("A", {}).get("frac_not_survived", 0.0))
    frac_B_not = float(neg.get("B", {}).get("frac_not_survived", 0.0))
    g1_pass = frac_E >= THRESH and frac_A_not >= THRESH and frac_B_not >= THRESH

    a, b = g2a["control"], g2b["control"]
    comb_fp = a["n_false_positives"] + b["n_false_positives"]
    comb_n = a["n_segments"] + b["n_segments"]
    comb_fpr = comb_fp / comb_n if comb_n else 1.0
    g2_pass = bool(a["fpr_ok"]) and bool(b["fpr_ok"]) and comb_fpr <= MAX_FPR

    passed = g1_pass and g2_pass
    commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=ROOT).stdout.strip()
    verdict = "BRIGHT_LINE_PASSED" if passed else "BRIGHT_LINE_NOT_PASSED"

    summary = {
        "schema": "bsff.bright_line_summary/v2",
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "git_commit": commit,
        "statistic_id": g1["protocol"]["statistic_id"],
        "thresholds": {"min_frac": THRESH, "max_fpr": MAX_FPR, "alpha": 0.05},
        "G1": {"frac_survived_E": frac_E, "frac_A_not_survived": frac_A_not,
               "frac_B_not_survived": frac_B_not, "G1_PASS": g1_pass,
               "n_surrogates": g1["protocol"]["n_surrogates"],
               "artifact": str(G1.relative_to(ROOT)), "sha256": _sha(G1)},
        "G2": {"fpr_A": a["fpr"], "fpr_B": b["fpr"], "combined_fpr": round(comb_fpr, 4),
               "G2_PASS": g2_pass, "artifacts": {"A": str(G2A.relative_to(ROOT)), "B": str(G2B.relative_to(ROOT))},
               "sha256": {"A": _sha(G2A), "B": _sha(G2B)}},
        "BRIGHT_LINE_PASSED": passed, "verdict": verdict,
        "chain_to_bnci2014_001": "UNLOCKED" if passed else "BLOCKED",
        "statement": ("BRIGHT LINE PASSED: real positive control and real-spectrum negative controls passed."
                      if passed else
                      "BRIGHT LINE NOT PASSED: operating characteristic on real neural data remains unproven."),
    }
    (BL / "BRIGHT_LINE_SUMMARY.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    md = f"""<!-- GENERATED by aggregate_verdict.py — do not edit by hand. -->
# Bonn bright-line — formal verdict

**{verdict}** — chain to BNCI2014-001 is **{summary['chain_to_bnci2014_001']}**.

Statistic: `{summary['statistic_id']}` · thresholds pre-declared (frac ≥ {THRESH}, FPR ≤ {MAX_FPR}, alpha 0.05).

## G1 — Bonn positive control (real ictal vs healthy)
- Set E (ictal) SURVIVED: **{frac_E:.2f}** (≥ {THRESH}?)
- Set A not-SURVIVED: **{frac_A_not:.2f}** (≥ {THRESH}?) · Set B not-SURVIVED: **{frac_B_not:.2f}** (≥ {THRESH}?)
- **G1_PASS = {g1_pass}** · n_surrogates = {g1['protocol']['n_surrogates']}
- artifact `{G1.relative_to(ROOT)}` sha256 `{_sha(G1)[:16]}…`

## G2 — spectrum-matched AR negative control (same SampEn instrument)
- FPR A = **{a['fpr']}**, FPR B = **{b['fpr']}**, combined = **{comb_fpr:.4f}** (≤ {MAX_FPR}?)
- **G2_PASS = {g2_pass}**
- artifacts `{G2A.relative_to(ROOT)}`, `{G2B.relative_to(ROOT)}`

## Limitations
Not clinical. Not diagnostic. Not regulatory. Not final proof of brain nonlinear
dynamics. Not a universal BCI benchmark. One benchmark (Bonn), one statistic.
A negative result is a valid operating-characteristic finding.
"""
    (ROOT / "docs" / "validation" / "BRIGHT_LINE_VERDICT.md").write_text(md, encoding="utf-8")
    print(verdict)
    print(f"  G1: E={frac_E:.2f} A_not={frac_A_not:.2f} B_not={frac_B_not:.2f} (≥{THRESH}) -> {g1_pass}")
    print(f"  G2: FPR_A={a['fpr']} FPR_B={b['fpr']} combined={comb_fpr:.4f} (≤{MAX_FPR}) -> {g2_pass}")
    return 0 if passed else 2


if __name__ == "__main__":
    raise SystemExit(main())
