#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab
"""S2 aggregation (Phase K): confirmatory verdict -> S2_BRIGHT_LINE_SUMMARY.json + S2_VERDICT.md.

S2_G1_PASS = E>=0.80 AND A_not>=0.80 AND B_not>=0.80
S2_G2_PASS = combined_FPR <= 0.05
S2_BRIGHT_LINE_PASSED = S2_G1_PASS AND S2_G2_PASS
"""

from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONF = ROOT / "artifacts/bonn_bright_line/s2_CONFIRMATORY_VERDICT.json"
LOCK = ROOT / "artifacts/bonn_bright_line/S2_SELECTION_LOCK.json"
SUMMARY = ROOT / "artifacts/bonn_bright_line/S2_BRIGHT_LINE_SUMMARY.json"
VERDICT_MD = ROOT / "docs/validation/S2_VERDICT.md"


def main() -> int:
    if not CONF.is_file():
        print("BLOCKED: confirmatory verdict missing")
        return 3
    c = json.loads(CONF.read_text())
    if c.get("S2_SELECTION") == "NONE" or c.get("verdict") == "S2_BLOCKED_NO_CANDIDATE":
        SUMMARY.write_text(
            json.dumps(
                {"final_state": "S2_BLOCKED_NO_CANDIDATE", "reason": c.get("reason")}, indent=2
            )
        )
        print("S2_BLOCKED_NO_CANDIDATE")
        return 3
    g1, g2 = c["G1"], c["G2"]
    passed = bool(c["S2_BRIGHT_LINE_PASSED"])
    verdict = c["verdict"]
    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip()
    summary = {
        "schema": "bsff.s2_bright_line_summary/v1",
        "final_state": verdict,
        "candidate": c["candidate"],
        "S2_G1_PASS": c["S2_G1_PASS"],
        "S2_G2_PASS": c["S2_G2_PASS"],
        "S2_BRIGHT_LINE_PASSED": passed,
        "G1": g1,
        "G2": g2,
        "thresholds": {"G1_min": 0.80, "G2_max_fpr": 0.05, "alpha": 0.05},
        "n_segments": c["n_segments"],
        "n_surrogates": c["n_surrogates"],
        "chain_to_bnci2014_001": "UNLOCKED" if passed else "BLOCKED",
        "selection_lock": json.loads(LOCK.read_text()) if LOCK.is_file() else None,
        "limitations": [
            "Single benchmark (Bonn); confirmatory n_surrogates=199 (compute-bound).",
            "S2-C1 is a conservative-threshold variant of SampEn; not a new statistic.",
            "Not externally replicated; not clinical/regulatory.",
        ],
        "forbidden_claims": [
            "clinical diagnosis",
            "medical use",
            "regulatory validation",
            "final proof of brain nonlinear dynamics",
            "universal BCI benchmark authority",
        ],
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "git_commit": commit,
    }
    SUMMARY.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    md = f"""<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- GENERATED by s2_aggregate.py — do not edit by hand. -->
# S2 specificity — verdict

**{verdict}** · candidate `{c["candidate"]}` · chain to BNCI2014-001 **{
        summary["chain_to_bnci2014_001"]
    }**.

## Confirmatory (n_segments={c["n_segments"]}, n_surrogates={c["n_surrogates"]})
- G1: E SURVIVED **{g1["E_survived_fraction"]}**, A not-SURVIVED **{
        g1["A_not_survived_fraction"]
    }**,
  B not-SURVIVED **{g1["B_not_survived_fraction"]}** (≥ 0.80) → S2_G1_PASS = **{c["S2_G1_PASS"]}**
- G2: AR-null FPR A **{g2["FPR_A"]}**, B **{g2["FPR_B"]}**, combined **{
        g2["combined_FPR"]
    }** (≤ 0.05)
  → S2_G2_PASS = **{c["S2_G2_PASS"]}**
- **S2_BRIGHT_LINE_PASSED = {passed}**

## Interpretation
{
        (
            "S2 closes the G2 specificity gap that blocked S1 while preserving G1 power. The bright line "
            "is crossed under the frozen protocol; BNCI2014-001 preregistration may proceed."
            if passed
            else "The frozen S2 candidate did not satisfy G1+G2 at confirmatory scale. The bright line remains "
            "uncrossed; BNCI2014-001 stays blocked. Other registered candidates (e.g. S2-C3-fdr) are "
            "candidates for an S3 round under a fresh pre-registration — not a post-hoc switch here."
        )
    }

## Limitations
Not clinical, diagnostic, regulatory. Single benchmark; conservative-threshold variant.
"""
    VERDICT_MD.write_text(md, encoding="utf-8")
    print(f"{verdict} | G1={c['S2_G1_PASS']} G2={c['S2_G2_PASS']}")
    return 0 if passed else 2


if __name__ == "__main__":
    raise SystemExit(main())
