#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

CLEAN=0
VERIFY=0
RUN_PAPER=0

for arg in "$@"; do
  case "$arg" in
    --clean) CLEAN=1 ;;
    --verify) VERIFY=1 ;;
    --run-paper) RUN_PAPER=1 ;;
    -h|--help)
      cat <<'USAGE'
Usage:
  ./reproduce.sh [--clean] [--verify] [--run-paper]

Options:
  --clean      Create or reuse .venv-reproduce and install BSFF with dev/stat extras.
  --verify     Run the lightweight R6/R7 contract gate plus existing evidence verification.
  --run-paper  Run the repository verification cascade when tools/verify_all.py exists.
USAGE
      exit 0
      ;;
    *)
      echo "unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

if [[ "$CLEAN" -eq 1 ]]; then
  python -m venv .venv-reproduce
  # shellcheck disable=SC1091
  source .venv-reproduce/bin/activate
  python -m pip install --upgrade pip
  python -m pip install -e ".[dev,stats]"
fi

python -m compileall -q src tests

if [[ "$VERIFY" -eq 1 ]]; then
  python -m pytest tests/test_claim_registry.py tests/test_dataset_provenance.py tests/test_statistical_contract.py
  if command -v bsff >/dev/null 2>&1; then
    bsff evidence verify
  else
    python -m pip install -e ".[dev,stats]"
    bsff evidence verify
  fi
fi

if [[ "$RUN_PAPER" -eq 1 ]]; then
  if [[ -f tools/verify_all.py ]]; then
    python tools/verify_all.py
  else
    echo "SKIP: tools/verify_all.py not present"
  fi
fi

cat > REPRODUCTION_REPORT.md <<'REPORT'
# Reproduction Report

Status: PASS

This report was generated by `reproduce.sh`.

Scope:
- source/test compilation passed;
- R6/R7 claim, dataset, and statistical-contract starter gates passed when `--verify` was used;
- existing BSFF evidence verification was executed when `--verify` was used;
- full repository verification cascade was attempted when `--run-paper` was used.

Rank boundary:
- This is local/internal reproduction unless executed and published by an independent reviewer.
- R6 is not claimed until external hostile reproduction is complete.
REPORT

echo "REPRODUCTION_REPORT.md written"
