#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

CLEAN=0
VERIFY=0
RUN_PAPER=0

for arg in "$@"; do
  case "$arg" in
    --clean) CLEAN=1 ;;
    --verify) VERIFY=1 ;;
    --run-paper) RUN_PAPER=1 ;;
    -h|--help)
      cat <<'USAGE'
Usage:
  ./reproduce.sh [--clean] [--verify] [--run-paper]

Options:
  --clean      Create or reuse .venv-reproduce and install BSFF with dev/stat extras.
  --verify     Run the R6/R7 master gate plus existing evidence verification.
  --run-paper  Run the repository verification cascade when tools/verify_all.py exists.
USAGE
      exit 0
      ;;
    *)
      echo "unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

if [[ "$CLEAN" -eq 1 ]]; then
  python -m venv .venv-reproduce
  # shellcheck disable=SC1091
  source .venv-reproduce/bin/activate
  python -m pip install --upgrade pip
  python -m pip install -e ".[dev,stats]"
fi

# `set -euo pipefail` is active: any verification command below that fails aborts
# the script *before* the report is written, so reaching a step means it passed.
# Status is therefore derived from which steps actually executed — never asserted.
python -m compileall -q src tests tools/validate_r6_contracts.py

STEPS=("source/test/tool compilation")

if [[ "$VERIFY" -eq 1 ]]; then
  python tools/validate_r6_contracts.py
  STEPS+=("R6/R7 master contract gate")
  python -m pytest \
    tests/test_claim_registry.py \
    tests/test_dataset_provenance.py \
    tests/test_statistical_contract.py \
    tests/test_r6_contracts_tool.py
  STEPS+=("claim / dataset / statistical-contract / master-gate tests")
  if ! command -v bsff >/dev/null 2>&1; then
    python -m pip install -e ".[dev,stats]"
  fi
  bsff evidence verify
  STEPS+=("bsff evidence verify")
  # Artifact hash / no-drift verification — the exact gate CI runs as
  # `artifact-hash-check`: generated evidence must be byte-reproducible.
  python tools/generate_manifest.py --check
  python tools/generate_sbom.py --check
  STEPS+=("artifact hash / no-drift verification (manifest + SBOM)")
fi

PAPER_STATUS="not requested"
if [[ "$RUN_PAPER" -eq 1 ]]; then
  if [[ -f tools/verify_all.py ]]; then
    python tools/verify_all.py
    PAPER_STATUS="executed"
    STEPS+=("full repository verification cascade")
  else
    # Requested but unavailable: this is a gap, not a pass. Recorded, not hidden.
    PAPER_STATUS="requested but tools/verify_all.py absent (NOT run)"
  fi
fi

# PASS only when the full verification path actually executed. Absent --verify,
# or a requested-but-skipped cascade, downgrades to PARTIAL — never PASS.
if [[ "$VERIFY" -eq 1 && ! ( "$RUN_PAPER" -eq 1 && "$PAPER_STATUS" != "executed" ) ]]; then
  STATUS="PASS"
else
  STATUS="PARTIAL"
fi

{
  echo "# Reproduction Report"
  echo
  echo "Status: ${STATUS}"
  echo
  echo "Generated by \`reproduce.sh\`. Status is PASS only when the full"
  echo "verification path (contract gate + pytest gates + \`bsff evidence verify\`"
  echo "+ artifact hash verification) actually executed; otherwise PARTIAL."
  echo
  echo "Verification steps that actually executed:"
  for step in "${STEPS[@]}"; do
    echo "- ${step};"
  done
  echo "- full repository verification cascade: ${PAPER_STATUS}."
  echo
  echo "Rank boundary:"
  echo "- This is local/internal reproduction unless executed and published by an independent reviewer."
  echo "- R6 is not claimed until external hostile reproduction is complete."
} > REPRODUCTION_REPORT.md

echo "REPRODUCTION_REPORT.md written (Status: ${STATUS})"
