# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab
"""Build (or --check) DEMONSTRATION.md — the one-command, self-proving front door.

A reviewer should be able to run a single command and watch the instrument prove
itself: the honesty gate passes, the self-falsification controls pass, a real
falsification is on record, and the contract is self-conformant — every line
generated from a machine verdict, never typed. The page is committed and a
``--check`` mode (CI-enforced) fails if it drifts from the live verdicts, so the
demonstration cannot go stale and cannot lie.

    python tools/build_demonstration.py            # regenerate DEMONSTRATION.md
    python tools/build_demonstration.py --check     # CI gate: in sync with reality
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "DEMONSTRATION.md"
BUNDLE = ROOT / "artifacts" / "demonstration"


def _run(cmd: list[str]) -> int:
    return subprocess.run(
        [sys.executable, str(ROOT / cmd[0]), *cmd[1:]],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    ).returncode


def _read_json(rel: str) -> dict:
    p = ROOT / rel
    return json.loads(p.read_text(encoding="utf-8")) if p.is_file() else {}


def _status_count() -> str:
    m = re.search(
        r"Live test count \| \*\*(\d+)\*\*", (ROOT / "STATUS.md").read_text(encoding="utf-8")
    )
    return m.group(1) if m else "?"


def gather() -> dict:
    # one honesty-gate run produces the sub-artifacts (claim-audit, controls, conformance)
    honesty_exit = _run(["tools/verify_honesty.py"])
    honesty = _read_json("artifacts/honesty/HONESTY_GATE.json")
    controls = _read_json("artifacts/controls/controls.json")
    conf = _read_json("artifacts/conformance/CONFORMANCE_VERDICT.json")
    loso = _read_json("research/bci_generalization/result_bnci2014_001_sub1-2.json")
    return {
        "honesty_ok": bool(honesty.get("all_ok")) and honesty_exit == 0,
        "honesty_checks": [{"check": c["check"], "ok": c["ok"]} for c in honesty.get("checks", [])],
        "control_negative": controls.get("negative", {}).get("verdict"),
        "control_positive": controls.get("positive", {}).get("verdict"),
        "controls_ok": bool(controls.get("controls_ok")),
        "conformance_overall": conf.get("overall"),
        "conformant": conf.get("conformant"),
        "unverifiable": conf.get("unverifiable"),
        "nonconformant": conf.get("nonconformant"),
        "loso_within": round(loso["within_mean"], 3)
        if loso.get("within_mean") is not None
        else None,
        "loso_cross": round(loso["cross_subject_loso_mean"], 3)
        if loso.get("cross_subject_loso_mean") is not None
        else None,
        "loso_gap": round(loso["loso_gap"], 3) if loso.get("loso_gap") is not None else None,
        "test_count": _status_count(),
    }


def render(d: dict) -> str:
    checks = "\n".join(
        f"| {c['check']} | {'PASS' if c['ok'] else 'FAIL'} |" for c in d["honesty_checks"]
    )
    return f"""<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab -->
<!-- GENERATED by tools/build_demonstration.py — do not edit by hand; run --check in CI. -->

# BSFF — demonstration

One command, and the instrument proves itself. Every value below is generated
from a machine verdict; `tools/build_demonstration.py --check` fails if any line
drifts from reality.

```bash
python tools/build_demonstration.py
```

## 1. The instrument cannot ship a decorative lie

Honesty gate (`tools/verify_honesty.py`): **{"PASS" if d["honesty_ok"] else "FAIL"}**

| sub-check | result |
|-----------|--------|
{checks}

## 2. It fails and passes correctly on ground truth

| self-falsification control | verdict | required |
|----------------------------|---------|----------|
| negative (white noise) | {d["control_negative"]} | not SURVIVED |
| positive (Hénon) | {d["control_positive"]} | SURVIVED |

Controls hold: **{d["controls_ok"]}**

## 3. A real falsification is on record

BNCI2014_001 motor imagery, CSP+LDA, leave-one-subject-out:

- within-subject: **{d["loso_within"]}**
- cross-subject (LOSO): **{d["loso_cross"]}**
- generalization gap: **{d["loso_gap"]}** (chance 0.5)

The within-subject accuracy does not survive honest cross-subject evaluation.
Scope is honest: n=2, a measurement, not a population proof (see `CLAIM_AUDIT.md`).

## 4. It verifies itself against its own contract

Self-conformance (`tools/run_contract_conformance.py`): **{d["conformance_overall"]}** —
{d["conformant"]} conformant, {d["nonconformant"]} nonconformant, {d["unverifiable"]} unverifiable
(blocked work named, not faked).

## State

- tests: **{d["test_count"]}** (generated by `tools/update_status.py`)
- full evidence: `CLAIM_AUDIT.md`, `EVIDENCE_INDEX.md`, `docs/HONESTY_AUTOMATION.md`
- nothing here is "true": the ceiling is *survived falsification under stated conditions*.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    data = gather()
    page = render(data)

    BUNDLE.mkdir(parents=True, exist_ok=True)
    (BUNDLE / "demonstration.json").write_text(json.dumps(data, indent=2), encoding="utf-8")
    (BUNDLE / "DEMONSTRATION.sha256").write_text(
        hashlib.sha256(page.encode("utf-8")).hexdigest() + "\n", encoding="utf-8"
    )

    if args.check:
        current = DEMO.read_text(encoding="utf-8") if DEMO.is_file() else ""
        if current != page:
            print("DEMONSTRATION.md is STALE — run: python tools/build_demonstration.py")
            return 1
        print("DEMONSTRATION.md: in sync")
        return 0

    DEMO.write_text(page, encoding="utf-8")
    print(
        f"Wrote DEMONSTRATION.md (honesty={data['honesty_ok']}, controls={data['controls_ok']}, "
        f"conformance={data['conformance_overall']}, tests={data['test_count']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
