# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab
"""Build (or --check) CORE.md — the generated architecture map.

One generated map of the whole verification stack: each layer, what it proves,
the tool that enforces it, and its live verdict — folding the independent gates
into a single navigable core. Generated from machine verdicts and --check'd in
CI, so the presentation cannot drift from the system it describes.

    python tools/build_core.py            # regenerate CORE.md
    python tools/build_core.py --check     # CI: the core map matches reality
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "CORE.md"


def _json(rel: str) -> dict:
    p = ROOT / rel
    return json.loads(p.read_text(encoding="utf-8")) if p.is_file() else {}


def gather() -> dict:
    # decision_gate cascades the whole stack (honesty gate + certificate) and writes every artifact
    subprocess.run(
        [sys.executable, str(ROOT / "tools" / "decision_gate.py")],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    decision = _json("artifacts/decision/decision.json")
    honesty = _json("artifacts/honesty/HONESTY_GATE.json")
    cert = _json("artifacts/certificate/CERTIFICATE.json")
    conf = _json("artifacts/conformance/CONFORMANCE_VERDICT.json")
    controls = _json("artifacts/controls/controls.json")
    hck = {c["check"]: c["ok"] for c in honesty.get("checks", [])}

    def mark(ok: bool) -> str:
        return "green" if ok else "RED"

    layers = [
        (
            "1 · Adjudication pipeline + 7 axioms",
            "deterministic, fail-closed verdicts",
            "tests/test_invariants.py",
            "enforced",
        ),
        (
            "2 · Self-falsification controls",
            "fails AND passes correctly on ground truth",
            "tools/verify_controls.py",
            mark(bool(controls.get("controls_ok"))),
        ),
        (
            "3 · Null + threshold registries",
            "no p-value without a null; no unsourced threshold",
            "tools/validate_{null,threshold}_registry.py",
            mark(
                hck.get("null_hypotheses_explicit", False)
                and hck.get("thresholds_have_provenance", False)
            ),
        ),
        (
            "4 · Grounding",
            "every prose number re-derives from its artifact",
            "tools/verify_grounding.py",
            mark(hck.get("grounding_numbers_match_artifacts", False)),
        ),
        (
            "5 · Self-conformance",
            "every contract promise met or honestly UNVERIFIABLE",
            "tools/run_contract_conformance.py",
            str(conf.get("overall", "?")),
        ),
        (
            "6 · Honesty gate",
            "a decorative lie cannot merge",
            "tools/verify_honesty.py",
            mark(bool(honesty.get("all_ok"))),
        ),
        (
            "7 · Demonstration",
            "one command, the instrument proves itself",
            "tools/build_demonstration.py",
            "generated + synced",
        ),
        (
            "8 · Release certificate",
            "the whole ordered chain certifies to one root",
            "tools/certify_release.py",
            str(cert.get("overall", "?")),
        ),
        (
            "9 · Decision gate",
            "does the idea earn investment?",
            "tools/decision_gate.py",
            str(decision.get("recommendation", "?")),
        ),
    ]
    return {
        "layers": layers,
        "recommendation": decision.get("recommendation"),
        "loso_gap": decision.get("loso_gap"),
        "conformance_overall": conf.get("overall"),
    }


def render(d: dict) -> str:
    rows = "\n".join(
        f"| **{name}** | {proves} | `{tool}` | {verdict} |"
        for name, proves, tool, verdict in d["layers"]
    )
    return f"""<!-- SPDX-License-Identifier: CC-BY-4.0 -->
<!-- Copyright (c) 2026 Yaroslav Vasylenko / neuron7xLab -->
<!-- GENERATED by tools/build_core.py — do not edit by hand; run --check in CI. -->

# BSFF — architecture map

BSFF is a layered verification system, not a loose collection of scripts. Each layer enforces a
property the layer below cannot fake, and the top layer turns the whole stack into
a single investment decision. Every verdict in this map is generated from a machine
artifact, and `tools/build_core.py --check` fails if this page drifts from reality.

## One command proves the core

```bash
python tools/verify_all.py
```

It cascades every layer — controls, registries, grounding, conformance, the honesty
gate, the certificate chain — and ends on the derived go/no-go recommendation.

## The stack

| layer | what it proves | enforced by | live verdict |
|-------|----------------|-------------|--------------|
{rows}

## Where it stands

- decision: **{d["recommendation"]}** — go to production as a falsification
  *instrument* and demarcation tool, not as a clinical/regulatory authority
  (see [`DECISION.md`](DECISION.md)).
- it does something real: a published within-subject BCI accuracy does not survive
  honest cross-subject evaluation — LOSO generalization gap **{d["loso_gap"]}**.
- it is honest about its limits: self-conformance is **{d["conformance_overall"]}**
  — the network/GPU/external legs are named `UNVERIFIABLE`, never faked.

## Related documents

- [`DECISION.md`](DECISION.md) — does the idea earn investment? (derived go/no-go)
- [`DEMONSTRATION.md`](DEMONSTRATION.md) — one-command self-proof for a reviewer
- [`CLAIM_AUDIT.md`](CLAIM_AUDIT.md) — every claim → command, value, status
- [`docs/HONESTY_AUTOMATION.md`](docs/HONESTY_AUTOMATION.md) — why it cannot lie
- [`docs/CERTIFICATE.md`](docs/CERTIFICATE.md) — the chained root over all streams

Proving a repository behaves as a falsification instrument is decomposed into
machine-checked properties, chained into one root that fails if any link lies.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    page = render(gather())
    if args.check:
        current = CORE.read_text(encoding="utf-8") if CORE.is_file() else ""
        if current != page:
            print("CORE.md is STALE — run: python tools/build_core.py")
            return 1
        print("CORE.md: in sync")
        return 0
    CORE.write_text(page, encoding="utf-8")
    print("Wrote CORE.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
